name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  validate_gradle:
    name: Validate Gradle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v2
  build:
    name: Build
    needs: [validate_gradle]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle Caching
        uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_USER }}
          ORG_GRADLE_PROJECT_mavenCentralPassword:  ${{ secrets.MAVEN_PASSWORD }}
  submit_dependencies:
    name: Submit dependencies to GitHub
    runs-on: ubuntu-latest
    needs: [validate_gradle]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v3
